language: php
php:
  - '7.0'
install: php composer install
after_success:
    "curl --ftp-create-dirs -T figgins -u $SFTP_USER:$SFTP_PASSWORD sftp://figgins.sftp.wpengine.com:2222/wp-content/plugins"
