language: php
php:
  - '7.0'
install: "composer install"
script: true
after_success:
    "curl --ftp-create-dirs -T '.' -u $SFTP_USER:$SFTP_PASSWORD sftp://figgins.sftp.wpengine.com:2222/wp-content/plugins/figgins <<< ls -R . | awk '/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,``);s=$0;f=1;next}NF&&f{ print s`/`$0 }'
